apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress-cost-management-system
  namespace: cost-management-system
spec:
  rules:
  - host: cost-management.moladin.com
    http:
      paths:
      - backend:
          service:
            name: cost-management-system-svc
            port:
              number: 5005
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - cost-management.moladin.com
    secretName: wildcard-moladin-tls
